Started logging messages at Sat Aug 30 06:40:22 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 42 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 95
Info:            Created 
Info:        Working on 96
Info:            Created 
Info:        Working on 161
Info:            Created 
Info:        Working on 162
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 242
Info:            Created 
Info:        Working on 246
Info:            Created 
Info:        Working on 233
Info:            Created 
Info:        Working on 234
Info:            Created 
Info:        Working on 329
Info:            Created 
Info:        Working on 333
Info:            Created 
Info:        Working on 320
Info:            Created 
Info:        Working on 321
Info:            Created 
Info:        Working on 423
Info:            Created 
Info:        Working on 427
Info:            Created 
Info:        Working on 6
Info:            Created 
Info:        Working on 123
Info:            Created 
Info:        Working on 124
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 204
Info:            Created 
Info:        Working on 202
Info:            Created 
Info:        Working on 203
Info:            Created 
Info:        Working on 295
Info:            Created 
Info:        Working on 298
Info:            Created 
Info:        Working on 287
Info:            Created 
Info:        Working on 288
Info:            Created 
Info:        Working on 396
Info:            Created 
Info:        Working on 400
Info:            Created 
Info:        Working on 387
Info:            Created 
Info:        Working on 388
Info:            Created 
Info:        Working on 492
Info:            Created 
Info:        Working on 496
Info:            Created 
Info:        Working on 9
Info:            Created 
Info:        Working on 14
Info:            Created 
Info:        Working on 25
Info:            Created 
Info:        Working on 52
Info:            Created 
Info:        Working on 98
Info:            Created 
Info:        Working on 516
Info:            Created 
Info:        Working on 518
Info:            Created 
Info:        Working on 167
Info:            Created 
Info:        Working on 471
Info:            Created 
Info:        Working on 629
Info:            Created 
Info:        Working on 630
Info:            Created 
Info:        Working on 473
Info:            Created 
Info:        Working on 167
Info:            Created 
Info:        Working on 414
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 368
Info:            Created 
Info:        Working on 350
Info:            Created 
Info:        Working on 415
Info:            Created 
Info:        Working on 356
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 363
Info:            Created 
Info:        Working on 481
Info:            Created 
Info:        Working on 483
Info:            Created 
Info:        Working on 257
Info:            Created 
Info:        Working on 370
Info:            Created 
Info:        Working on 484
Info:            Created 
Info:        Working on 356
Info:            Created 
Info:        Working on 475
Info:            Created 
Info:        Working on 574
Info:            Created 
Info:        Working on 592
Info:            Created 
Info:        Working on 594
Info:            Created 
Info:        Working on 552
Info:            Created 
Info:        Working on 554
Info:            Created 
Info:        Working on 649
Info:            Created 
Info:        Working on 650
Info:            Created 
Info:        Working on 556
Info:            Created 
Info:        Working on 552
Info:            Created 
Info:        Working on 511
Info:            Created 
Info:        Working on 446
Info:            Created 
Info:        Working on 464
Info:            Created 
Info:        Working on 446
Info:            Created 
Info:        Working on 512
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 459
Info:            Created 
Info:        Working on 564
Info:            Created 
Info:        Working on 567
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 452
Info:            Created 
Info:        Working on 558
Info:            Created 
Info:        Working on 624
Info:            Created 
Info:        Working on 627
Info:            Created 
Info:        Working on 638
Info:            Created 
Info:        Working on 634
Info:            Created 
Info:        Working on 636
Info:            Created 
Info:        Working on 602
Info:            Created 
Info:        Working on 604
Info:            Created 
Info:        Working on 653
Info:            Created 
Info:        Working on 654
Info:            Created 
Info:        Working on 606
Info:            Created 
Info:        Working on 602
Info:            Created 
Info:        Working on 587
Info:            Created 
Info:        Working on 526
Info:            Created 
Info:        Working on 544
Info:            Created 
Info:        Working on 526
Info:            Created 
Info:        Working on 588
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 539
Info:            Created 
Info:        Working on 614
Info:            Created 
Info:        Working on 616
Info:            Created 
Info:        Working on 438
Info:            Created 
Info:        Working on 546
Info:            Created 
Info:        Working on 617
Info:            Created 
Info:        Working on 532
Info:            Created 
Info:        Working on 608
Info:            Created 
Info:        Working on 645
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sat Aug 30 06:40:22 2014
